name: github-eslint
run-name: Running ESLint agaisy source code
on: [push]
jobs:
  run-eslint:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: action/setup-node@v3
        with:
          node-version: '20'
      - run: npm start
      - run: npx eslint *.js
