name: github-eslint
on:
  push:
    branches:
      - master

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Run ESLint
        run: npx eslint src/*.js
